name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: |
            {
              "githubUserName": "${{ github.repository_owner }}",
              "title": "",
              "backgroundColor": "#161b22",
              "foregroundColor": "#0d1117",
              "dataColor1": "#006d32",
              "dataColor2": "#26a641",
              "dataColor3": "#39d353",
              "guidelineColor": "#21262d",
              "textColor": "#8b949e",
              "type": "NORMAL"
            }

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
